apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.slug}}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: cedadev/${{ values.slug }}
    backstage.io/source-template: template:default/ceda-github-python-library
spec:
  type: library
  owner: user:${{ values.author.metadata.namespace }}/${{ values.author.metadata.name }}
  lifecycle: experimental
